name: sgdm
dependencies:
- appnope=0.1.0=py36_1000
- attrs=19.3.0=py_0
- backcall=0.1.0=py_0
- blas=1.0=mkl
- bleach=3.1.1=py_0
- bzip2=1.0.8=h0b31af3_2
- ca-certificates=2019.11.28=hecc5488_0
- cftime=1.0.4.2=py36h3b54f70_0
- cmocean=2.0=py_1
- colorspacious=1.1.2=pyh24bf2e0_0
- curl=7.65.3=h22ea746_0
- cycler=0.10.0=py36_0
- decorator=4.4.1=py_0
- defusedxml=0.6.0=py_0
- entrypoints=0.3=py36_1000
- freetype=2.10.0=h24853df_1
- gsw=3.3.1=py36h3b54f70_1
- hdf4=4.2.13=h84186c3_1003
- hdf5=1.10.5=nompi_h3e39495_1104
- importlib_metadata=1.5.0=py36_0
- ipykernel=5.1.4=py36h5ca1d4c_0
- ipython=7.12.0=py36h5ca1d4c_0
- ipython_genutils=0.2.0=py_1
- jedi=0.16.0=py36_0
- jinja2=2.11.1=py_0
- jpeg=9c=h1de35cc_1001
- json5=0.9.0=py_0
- jsonschema=3.2.0=py36_0
- jupyter_client=6.0.0=py_0
- jupyter_core=4.6.3=py36_0
- jupyterlab=1.2.6=py_0
- jupyterlab_server=1.0.6=py_0
- kiwisolver=1.1.0=py36ha1b3eb9_0
- krb5=1.16.4=h1752a42_0
- libblas=3.8.0=14_openblas
- libcblas=3.8.0=14_openblas
- libcurl=7.65.3=h16faf7d_0
- libcxx=9.0.1=1
- libedit=3.1.20170329=hcfe32e1_1001
- libffi=3.2.1=h6de7cb9_1006
- libgfortran=4.0.0=2
- liblapack=3.8.0=14_openblas
- libnetcdf=4.7.3=nompi_hec86efb_100
- libopenblas=0.3.7=h3d69b6c_6
- libpng=1.6.37=h2573ce8_0
- libsodium=1.0.17=h01d97ff_0
- libssh2=1.8.2=hcdc9a53_2
- llvm-openmp=9.0.1=h40edb58_0
- markupsafe=1.1.1=py36h1de35cc_0
- matplotlib=3.1.2=py36_1
- matplotlib-base=3.1.2=py36h11da6c2_1
- mistune=0.8.4=py36h1de35cc_1000
- nbconvert=5.6.1=py36_0
- nbformat=5.0.4=py_0
- ncurses=6.1=h0a44026_1002
- netcdf4=1.5.3=nompi_py36hcf2264a_102
- notebook=6.0.3=py36_0
- numpy=1.17.3=py36hde6bac1_0
- openssl=1.1.1d=h0b31af3_0
- pandas=0.25.3=py36h4f17bb1_0
- pandoc=2.9.2=0
- pandocfilters=1.4.2=py_1
- parso=0.6.1=py_0
- pexpect=4.8.0=py36_0
- pickleshare=0.7.5=py36_1000
- pip=9.0.1=py36_1
- prometheus_client=0.7.1=py_0
- prompt_toolkit=3.0.3=py_0
- ptyprocess=0.6.0=py_1001
- pygments=2.5.2=py_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pyrsistent=0.15.7=py36h0b31af3_0
- python=3.6.7=h4285619_1006
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- pyzmq=19.0.0=py36h4bf09a9_0
- readline=8.0=hcfe32e1_0
- scipy=1.4.1=py36h82752d6_0
- send2trash=1.5.0=py_0
- six=1.14.0=py36_0
- sqlite=3.30.1=h93121df_0
- terminado=0.8.3=py36_0
- testpath=0.4.4=py_0
- tk=8.6.10=hbbe82c9_0
- tornado=6.0.3=py36h0b31af3_0
- traitlets=4.3.3=py36_0
- viscm=0.7=pyh24bf2e0_0
- wcwidth=0.1.8=py_0
- webencodings=0.5.1=py_1
- wheel=0.29.0=py36_0
- xarray=0.14.1=py_1
- xz=5.2.4=h1de35cc_1001
- yaml=0.1.6=0
- zeromq=4.3.2=h6de7cb9_2
- zipp=3.0.0=py_0
- zlib=1.2.11=0
- certifi=2016.2.28=py36_0
- icu=54.1=0
- mkl=2017.0.3=0
- qt=5.6.2=2
- setuptools=36.4.0=py36_1
- sip=4.18=py36_0
- pip:
  - astral==1.10.1
  - docutils==0.16
  - glidertools==2019.5
  - importlib-metadata==1.5.0
  - ipython-genutils==0.2.0
  - joblib==0.14.1
  - jupyter-client==6.0.0
  - jupyter-core==4.6.3
  - jupyterlab-server==1.0.6
  - m2r==0.2.1
  - numexpr==2.7.1
  - prometheus-client==0.7.1
  - prompt-toolkit==3.0.3
  - scikit-learn==0.22.1
  - seawater==3.3.4
  - tqdm==4.41.1
prefix: /Users/kerfoot/miniconda3/envs/sgdm

